spring:
  application:
    name: auth-service

server:
  port: 0

#Eureka Client
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#Log

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator




