package com.co.technicaltest.infrastructure.mapper;

import org.springframework.stereotype.Component;

/**
 * Class for event data mapper generated by the accounts service
 *
 * @author andres on 2025/09/28.
 * @version 1.0.0
 */
@Component
public class AccountMessagingDataMapper {



}
