spring:
  application:
    name: customer-service
#Data base config
  jpa:
    generate-ddl: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
      password: sasa
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      url: jdbc:mysql://localhost:3306/db_cliente
#Oauth2 client
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service/oauth2/default
      client:
        registration:
          customer-service:
            provider: spring
            client-id: customer
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://customer-service/api/v1/usuarios/auth/authorized
            scope:
              - openid
              - profile
              - read
              - write
            client-name: customer-service
        provider:
          spring:
            issuer-uri: http://auth-service/oauth2/default


#Port
server:
  port: 0

#Eureka Client
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#Log
logging:
  file:
    path: /app/logs
  level:
    org:
      hibernate:
        SQL: debug

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator




