package com.co.technicaltest.account_service.domain.enums;

public enum EventType {
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_DELETED,
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    CUSTOMER_DELETED,
    TRANSACTION_INITIATED,
    TRANSACTION_APPROVED,
    TRANSACTION_REJECTED
}
